name: backstage
description: "Backstage"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  device_preview_plus: ^2.6.1
  http: ^1.2.2
  firebase_core: ^4.10.0
  firebase_auth: ^6.5.2
  cloud_firestore: ^6.5.0
  cupertino_icons: ^1.0.9
  table_calendar: ^3.2.1
  intl: ^0.20.2
  fl_chart: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  fake_cloud_firestore: 4.1.1
  firebase_auth_mocks: ^0.15.2

flutter:
  uses-material-design: true
